### ISSUE TITLE
install link not working

### ISSUE THREAD

**Issue by zaferyardimci** [duckzland/TGM-Plugin-Activation#2]
When I click on install link, dont work.

**Comment by zaferyardimci** [comment]
I fixed the issue.

change that:

wp_nonce_url(esc_url(

to

esc_url(wp_nonce_url(

line 1334

**Comment by duckzland** [comment]
I've made some changes regarding the esc_url for other place too, do let me know if something else breaks.

**Comment by zaferyardimci** [comment]
Thanks.

Update link not showing.

and I'm think you must add update system to version 2.1,
because fixed a ton bugs on new version.

**Comment by duckzland** [comment]
updating effort in progress : https://github.com/duckzland/TGM-Plugin-Activation/issues/3

**Comment by duckzland** [comment]
Try to use the master branch, it is taken from the latest development branch, it should work properly now
