### ISSUE TITLE
Do pull request to original repo?

### ISSUE THREAD

**Issue by pavot** [duckzland/TGM-Plugin-Activation#3]
Hi there,
you did amazing job adding plugins update functionality! Any chance to prepare a pull request to original repo? As I can see, class developer are welcome this feature https://github.com/thomasgriffin/TGM-Plugin-Activation/issues/318#issuecomment-95635899 

Thanks for you time!

**Comment by duckzland** [comment]
well right now it has to much difference with the original repo, if someone can help do this and submit pull to this repo, I'll forward the code to the original repo.

**Comment by swiderski** [comment]
I am on it!

**Comment by swiderski** [comment]
I did full merge of today version of origina TGMl + your version with update option. AS I don't know how to make pull request proper I will just post link to code that is done http://apollo13.kinsta.com/class-tgm-plugin-activation.txt just rename to *.php after downloading.

**Comment by pavot** [comment]
@swiderski amazing. Did you had a chance to test it?

**Comment by swiderski** [comment]
Yes, I have tested install, bulk install and bulk update. No errors, no notices. But if you could confirm it it would be great!

**Comment by pavot** [comment]
Bulk install returns "Fatal error: Class 'TGM_Bulk_Installer' not found " and I see no update links for plugins that I changed version number for... Here is screenshot: http://note.io/1HwlGvh 

One by one installs work as expected. Do you have 'Private Repository' or only from WP.org?

Not sure if it's my theme problem though. Will digg it further.

**Comment by swiderski** [comment]
AS far as I know, duckzland version never had these links. They were only present in first version that could be found on ThemeForest forums. I can wrong here however.

About Fatal error: I didn't see any, but I will check it again later, as I will be off now for few hours.

**Comment by swiderski** [comment]
I believe that adding these link, now that we have full merge with most current version, will be quite easy. But I will check it in few hours.

**Comment by zaferyardimci** [comment]
Hey guys,

I following this topic. I tested this http://apollo13.kinsta.com/class-tgm-plugin-activation.txt and worked perfect.

this will be perfect if you add "update" link bellow plugins headings.

**Comment by fireform** [comment]
@pavot 
Bulk_install bug https://github.com/thomasgriffin/TGM-Plugin-Activation/issues/185
Specify default slug in the config:
<pre>'menu' => 'tgmpa-install-plugins' </pre>

**Comment by swiderski** [comment]
OK I did merge with most current version from two hours ago. I can see in code that links for update and install are in code. I will now check why they don't appear. My version is here https://github.com/swiderski/TGM-Plugin-Activation

**Comment by fireform** [comment]
http://cl.ly/1j3R3X0X1V0l
I added links, but not working properly with bulk update. Updating succesfully pre-packeged plugins, but can't download and update from plugins repository: "Download failed. A valid URL was not provided". Maybe someone can take a look?

**Comment by swiderski** [comment]
@fireform I am working on merge of your version with my last commit. Not working for me yet but I will get back to it again. 
Btw there is issue in my last commit with protected method. I will have to check if original have same issue.

**Comment by duckzland** [comment]
@swiderski nice job, I've merged the changes. afaik the original author wants us to use the develop branch if we are going to merge this with the mainstream. Is this last code taken from the master release or the develop branch?

**Comment by swiderski** [comment]
@duckzland Thanks for it. I will try to work on your repo. Last merge I did was after master branch pulled from develop one. I will do now again merge, as they are highly active lately :-) and then I will try to bring up update link back to live.

**Comment by swiderski** [comment]
Ufff commit is done. You can test it and make pull request to original.

**Comment by pavot** [comment]
@swiderski tested on my install. Works perfectly great job!

**Comment by duckzland** [comment]
@swiderski I've merged the master with add_update_mode, so we got 2 different branches, one is master branch for the "old 2.4.xx branch with updating plugin added into" and the other is develop branch for the "new 2.5.xx branch with updating plugin feature", main stream can only accept the develop branch for pull request so I would suggest if the master is working enough, we leave that branch and work only on the develop branch so this can be merged to mainstream.

**Comment by duckzland** [comment]
Sorry tried to merge with mainstream but denied maybe other can fix this
