### ISSUE TITLE
Update bundled plugins

### ISSUE THREAD

**Issue by nomansbeauty** [duckzland/TGM-Plugin-Activation#7]
Hi,

Update bundled plugins notification - is this feature available in your TGM version?
I noticed that its not present in original TGM class. Can you please confirm.

Thanks so much.

**Comment by duckzland** [comment]
yes it is available but only if there is actually plugin to update and only tested with localy bundled file + using normal wp installation under a single wp install. do chime in if you found it is working under FTP install mode, not locally bundled file and multi site install

**Comment by nomansbeauty** [comment]
Thanks for prompt response :) So it means all plugins coming from WP repository are not going to show updates? (I think that is fine as WP shows it under dashboard tab). The important is to update plugins like: Visual Composer, Theme Core plugin etc... which seems covered.

I will try testing it our for multi-site.

Suggestion: Avada theme uses  TGM v2.3.6 they have added some custom code that handles this logic pretty well. You may mimic their logic to fine tune.

Thanks.

**Comment by duckzland** [comment]
afaik the class is using the array supplied by you when determining whether to update / install / activate the bundled plugins, the source of the plugin can be local zip, wp repo, and/ or custom repo but for this fork I only test for local zip as I only need one from local zip :)
