### ISSUE TITLE
Permissions error when attempting individual plugin upgrades

### ISSUE THREAD

**Issue by edbloom** [duckzland/TGM-Plugin-Activation#8]
Hi,

Great work. Think I found a bug.

So I tested this by adding an updated version of Visual Composer to my theme source. The correct prompt appears telling me to upgrade the plugin. Once the TGM screen opens I click this link
http://awesomescreenshot.com/08a4v8rf98

and I get this
http://awesomescreenshot.com/02b4v8ri69

this method
http://awesomescreenshot.com/0f14v8rod3

works just fine - which was odd I thought - any ideas?

**Comment by edbloom** [comment]
I should add - I've also checked the file permissions etc. are correct (644) and the path is obviously correct too.

**Comment by duckzland** [comment]
this is on single instance (not multi site) plus using direct method (not ftp method) ?

**Comment by edbloom** [comment]
single instance - yes
direct method - yes (as in the visual composer files are within the theme)

**Comment by duckzland** [comment]
ok I've pushed the latest commit to master seems to fix the bug

**Comment by edbloom** [comment]
@duckzland - perfect! Thanks a mill for the super quick fix :)
